// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvzvtssogqkoszgsowbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12enZ0c3NvZ3Frb3N6Z3Nvd2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mzg4MTYsImV4cCI6MjA2MjIxNDgxNn0.xkipzfRvcuHs0nZbg_fwv1osOOVP2jdbZy-S50Qgsho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);